name: Build and Push Docker Compose Services

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Build and Push Docker Compose Services to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Check out the repo
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx for multi-platform support (if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Install Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      # Step 5: Build and push the Docker Compose services
      - name: Build and Push Docker Compose Services
        run: |
          # Build and push each service defined in the docker-compose.yml file
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
